
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package pt.ruiandrade;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int AND = 4;
  public static final int XOR = 6;
  public static final int EQUIV = 8;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int VAR = 11;
  public static final int BOOLCONST = 12;
  public static final int IMPL = 7;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int NOT = 5;
  public static final int LPAREN = 9;
  public static final int OR = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "OR",
  "AND",
  "NOT",
  "XOR",
  "IMPL",
  "EQUIV",
  "LPAREN",
  "RPAREN",
  "VAR",
  "BOOLCONST"
  };
}

